export type TaxType = "vat" | "gst" | "sales_tax" | "none"

export interface InvoiceLanguage {
  id: string
  name: string
  flag: string
  texts: {
    // Headers and sections
    invoice: string
    paymentInformation: string
    notes: string

    // Invoice details
    issueDate: string
    dueDate: string
    referenceNumber: string
    customerReference: string
    orderNumber: string

    // Company information
    companyId: string
    vatId: string
    email: string
    website: string

    // Payment information
    paymentMethod: string
    bankAccount: string
    iban: string
    swiftBic: string

    // Payment methods
    paymentMethods: {
      cash: string
      bankTransfer: string
      paypal: string
      creditCard: string
      wise: string
      unknown: string
    }

    // Tax type labels (for PDF)
    taxTypes: {
      vat: { percent: string; amount: string; total: string; id: string }
      gst: { percent: string; amount: string; total: string; id: string }
      sales_tax: { percent: string; amount: string; total: string; id: string }
      none: { percent: string; amount: string; total: string; id: string }
    }

    // Table headers
    table: {
      description: string
      quantity: string
      unitPrice: string
      vatPercent: string
      netPrice: string
      vatAmount: string
      total: string
    }

    // Totals
    netTotal: string
    vatTotal: string
    totalDue: string
    paid: string

    // Reverse Charge
    reverseChargeText: string

    // Footer
    generatedBy: string
  }
}

export const invoiceLanguages: InvoiceLanguage[] = [
  {
    id: "en",
    name: "English",
    flag: "🇺🇸",
    texts: {
      invoice: "Invoice",
      paymentInformation: "Payment Information",
      notes: "Notes",

      issueDate: "Issue Date",
      dueDate: "Due Date",
      referenceNumber: "Reference Number",
      customerReference: "Customer Reference",
      orderNumber: "Order Number",

      companyId: "Company ID",
      vatId: "VAT ID",
      email: "Email",
      website: "Website",

      paymentMethod: "Payment Method",
      bankAccount: "Bank Account",
      iban: "IBAN",
      swiftBic: "SWIFT/BIC",

      paymentMethods: {
        cash: "Cash",
        bankTransfer: "Bank Transfer",
        paypal: "PayPal",
        creditCard: "Credit Card",
        wise: "Wise",
        unknown: "Unknown",
      },

      taxTypes: {
        vat: { percent: "VAT %", amount: "VAT Amount", total: "VAT Total", id: "VAT ID" },
        gst: { percent: "GST %", amount: "GST Amount", total: "GST Total", id: "GST ID" },
        sales_tax: { percent: "Tax %", amount: "Tax Amount", total: "Tax Total", id: "Tax ID" },
        none: { percent: "Tax %", amount: "Tax Amount", total: "Tax Total", id: "Tax ID" },
      },

      table: {
        description: "Description",
        quantity: "Quantity",
        unitPrice: "Unit Price",
        vatPercent: "VAT %",
        netPrice: "Net Price",
        vatAmount: "VAT Amount",
        total: "Total",
      },

      netTotal: "Net Total",
      vatTotal: "Tax Total",
      totalDue: "Total Due",
      paid: "PAID!",

      reverseChargeText: "Reverse Charge",

      generatedBy: "Generated by Invoice.wiki",
    },
  },
  {
    id: "de",
    name: "Deutsch",
    flag: "🇩🇪",
    texts: {
      invoice: "Rechnung",
      paymentInformation: "Zahlungsinformationen",
      notes: "Notizen",

      issueDate: "Rechnungsdatum",
      dueDate: "Fälligkeitsdatum",
      referenceNumber: "Referenznummer",
      customerReference: "Kundenreferenz",
      orderNumber: "Bestellnummer",

      companyId: "Firmen-ID",
      vatId: "USt-IdNr.",
      email: "E-Mail",
      website: "Website",

      paymentMethod: "Zahlungsart",
      bankAccount: "Bankkonto",
      iban: "IBAN",
      swiftBic: "SWIFT/BIC",

      paymentMethods: {
        cash: "Bargeld",
        bankTransfer: "Banküberweisung",
        paypal: "PayPal",
        creditCard: "Kreditkarte",
        wise: "Wise",
        unknown: "Unbekannt",
      },

      taxTypes: {
        vat: { percent: "MwSt %", amount: "MwSt-Betrag", total: "MwSt-Summe", id: "USt-IdNr." },
        gst: { percent: "GST %", amount: "GST-Betrag", total: "GST-Summe", id: "GST-Nr." },
        sales_tax: { percent: "Steuer %", amount: "Steuerbetrag", total: "Steuersumme", id: "Steuer-ID" },
        none: { percent: "Steuer %", amount: "Steuerbetrag", total: "Steuersumme", id: "Steuer-ID" },
      },

      table: {
        description: "Beschreibung",
        quantity: "Menge",
        unitPrice: "Einzelpreis",
        vatPercent: "MwSt %",
        netPrice: "Nettopreis",
        vatAmount: "MwSt-Betrag",
        total: "Gesamt",
      },

      netTotal: "Nettosumme",
      vatTotal: "Steuersumme",
      totalDue: "Gesamtbetrag",
      paid: "BEZAHLT!",

      reverseChargeText: "Reverse Charge",

      generatedBy: "Erstellt von Invoice.wiki",
    },
  },
  {
    id: "cs",
    name: "Čeština",
    flag: "🇨🇿",
    texts: {
      invoice: "Faktura",
      paymentInformation: "Platební informace",
      notes: "Poznámky",

      issueDate: "Datum vystavení",
      dueDate: "Datum splatnosti",
      referenceNumber: "Referenční číslo",
      customerReference: "Reference zákazníka",
      orderNumber: "Číslo objednávky",

      companyId: "IČO",
      vatId: "DIČ",
      email: "E-mail",
      website: "Webová stránka",

      paymentMethod: "Způsob platby",
      bankAccount: "Bankovní účet",
      iban: "IBAN",
      swiftBic: "SWIFT/BIC",

      paymentMethods: {
        cash: "Hotovost",
        bankTransfer: "Bankovní převod",
        paypal: "PayPal",
        creditCard: "Platební karta",
        wise: "Wise",
        unknown: "Neznámý",
      },

      taxTypes: {
        vat: { percent: "DPH %", amount: "Částka DPH", total: "Celkem DPH", id: "DIČ" },
        gst: { percent: "GST %", amount: "Částka GST", total: "Celkem GST", id: "GST ID" },
        sales_tax: { percent: "Daň %", amount: "Částka daně", total: "Celkem daň", id: "Daňové ID" },
        none: { percent: "Daň %", amount: "Částka daně", total: "Celkem daň", id: "Daňové ID" },
      },

      table: {
        description: "Popis",
        quantity: "Množství",
        unitPrice: "Jednotková cena",
        vatPercent: "DPH %",
        netPrice: "Cena bez DPH",
        vatAmount: "Částka DPH",
        total: "Celkem",
      },

      netTotal: "Celkem bez DPH",
      vatTotal: "Celkem daň",
      totalDue: "K úhradě",
      paid: "ZAPLACENO!",

      reverseChargeText: "Reverse Charge",

      generatedBy: "Vytvořeno Invoice.wiki",
    },
  },
  {
    id: "pl",
    name: "Polski",
    flag: "🇵🇱",
    texts: {
      invoice: "Faktura",
      paymentInformation: "Informacje o płatności",
      notes: "Uwagi",

      issueDate: "Data wystawienia",
      dueDate: "Termin płatności",
      referenceNumber: "Numer referencyjny",
      customerReference: "Referencja klienta",
      orderNumber: "Numer zamówienia",

      companyId: "NIP",
      vatId: "VAT ID",
      email: "E-mail",
      website: "Strona internetowa",

      paymentMethod: "Sposób płatności",
      bankAccount: "Konto bankowe",
      iban: "IBAN",
      swiftBic: "SWIFT/BIC",

      paymentMethods: {
        cash: "Gotówka",
        bankTransfer: "Przelew bankowy",
        paypal: "PayPal",
        creditCard: "Karta kredytowa",
        wise: "Wise",
        unknown: "Nieznany",
      },

      taxTypes: {
        vat: { percent: "VAT %", amount: "Kwota VAT", total: "Suma VAT", id: "NIP" },
        gst: { percent: "GST %", amount: "Kwota GST", total: "Suma GST", id: "GST ID" },
        sales_tax: { percent: "Podatek %", amount: "Kwota podatku", total: "Suma podatku", id: "ID podatkowe" },
        none: { percent: "Podatek %", amount: "Kwota podatku", total: "Suma podatku", id: "ID podatkowe" },
      },

      table: {
        description: "Opis",
        quantity: "Ilość",
        unitPrice: "Cena jednostkowa",
        vatPercent: "VAT %",
        netPrice: "Cena netto",
        vatAmount: "Kwota VAT",
        total: "Razem",
      },

      netTotal: "Suma netto",
      vatTotal: "Suma podatku",
      totalDue: "Do zapłaty",
      paid: "ZAPŁACONE!",

      reverseChargeText: "Reverse Charge",

      generatedBy: "Wygenerowane przez Invoice.wiki",
    },
  },
  {
    id: "sk",
    name: "Slovenčina",
    flag: "🇸🇰",
    texts: {
      invoice: "Faktúra",
      paymentInformation: "Platobné informácie",
      notes: "Poznámky",

      issueDate: "Dátum vystavenia",
      dueDate: "Dátum splatnosti",
      referenceNumber: "Referenčné číslo",
      customerReference: "Referencia zákazníka",
      orderNumber: "Číslo objednávky",

      companyId: "IČO",
      vatId: "IČ DPH",
      email: "E-mail",
      website: "Webová stránka",

      paymentMethod: "Spôsob platby",
      bankAccount: "Bankový účet",
      iban: "IBAN",
      swiftBic: "SWIFT/BIC",

      paymentMethods: {
        cash: "Hotovosť",
        bankTransfer: "Bankový prevod",
        paypal: "PayPal",
        creditCard: "Platobná karta",
        wise: "Wise",
        unknown: "Neznámy",
      },

      taxTypes: {
        vat: { percent: "DPH %", amount: "Suma DPH", total: "Celkom DPH", id: "IČ DPH" },
        gst: { percent: "GST %", amount: "Suma GST", total: "Celkom GST", id: "GST ID" },
        sales_tax: { percent: "Daň %", amount: "Suma dane", total: "Celkom daň", id: "Daňové ID" },
        none: { percent: "Daň %", amount: "Suma dane", total: "Celkom daň", id: "Daňové ID" },
      },

      table: {
        description: "Popis",
        quantity: "Množstvo",
        unitPrice: "Jednotková cena",
        vatPercent: "DPH %",
        netPrice: "Cena bez DPH",
        vatAmount: "Suma DPH",
        total: "Celkom",
      },

      netTotal: "Celkom bez DPH",
      vatTotal: "Celkom daň",
      totalDue: "K úhrade",
      paid: "ZAPLATENÉ!",

      reverseChargeText: "Reverse Charge",

      generatedBy: "Vytvorené Invoice.wiki",
    },
  },
  {
    id: "uk",
    name: "Українська",
    flag: "🇺🇦",
    texts: {
      invoice: "Рахунок-фактура",
      paymentInformation: "Платіжна інформація",
      notes: "Примітки",

      issueDate: "Дата виставлення",
      dueDate: "Дата оплати",
      referenceNumber: "Референс номер",
      customerReference: "Референс клієнта",
      orderNumber: "Номер замовлення",

      companyId: "ЄДРПОУ",
      vatId: "ПДВ номер",
      email: "Електронна пошта",
      website: "Веб-сайт",

      paymentMethod: "Спосіб оплати",
      bankAccount: "Банківський рахунок",
      iban: "IBAN",
      swiftBic: "SWIFT/BIC",

      paymentMethods: {
        cash: "Готівка",
        bankTransfer: "Банківський переказ",
        paypal: "PayPal",
        creditCard: "Кредитна картка",
        wise: "Wise",
        unknown: "Невідомо",
      },

      taxTypes: {
        vat: { percent: "ПДВ %", amount: "Сума ПДВ", total: "Всього ПДВ", id: "ПДВ номер" },
        gst: { percent: "GST %", amount: "Сума GST", total: "Всього GST", id: "GST ID" },
        sales_tax: { percent: "Податок %", amount: "Сума податку", total: "Всього податок", id: "Податковий ID" },
        none: { percent: "Податок %", amount: "Сума податку", total: "Всього податок", id: "Податковий ID" },
      },

      table: {
        description: "Опис",
        quantity: "Кількість",
        unitPrice: "Ціна за одиницю",
        vatPercent: "ПДВ %",
        netPrice: "Ціна без ПДВ",
        vatAmount: "Сума ПДВ",
        total: "Разом",
      },

      netTotal: "Всього без ПДВ",
      vatTotal: "Всього податок",
      totalDue: "До сплати",
      paid: "СПЛАЧЕНО!",

      reverseChargeText: "Reverse Charge",

      generatedBy: "Створено Invoice.wiki",
    },
  },
]

export const getInvoiceLanguageById = (id: string): InvoiceLanguage => {
  return invoiceLanguages.find((lang) => lang.id === id) || invoiceLanguages[0] // default to English
}
